# Generated by Django 3.1.7 on 2021-04-22 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organizacao',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.CharField(max_length=1000)),
                ('avatar', models.ImageField(upload_to='')),
                ('is_organizacao', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.CharField(max_length=1000)),
                ('local', models.CharField(max_length=500)),
                ('data', models.DateTimeField(verbose_name='data evento')),
                ('organizacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projeto.organizacao')),
            ],
        ),
    ]
